version: "3.8"

services:
  db-master:
    image: bitnami/postgresql-repmgr:15
    container_name: db-master
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=admin
      - POSTGRESQL_USERNAME=repuser
      - POSTGRESQL_PASSWORD=reppassword
      - POSTGRESQL_DATABASE=mydb
      - REPMGR_PASSWORD=reppassword
      - REPMGR_PRIMARY_HOST=db-master
      - REPMGR_NODE_ID=1
      - REPMGR_NODE_NAME=db-master-1
      - REPMGR_PARTNER_NODES=db-master,db-replica1,db-replica2
      - REPMGR_NODE_NETWORK_NAME=db-master
    ports:
      - "5432:5432"
    networks:
      - pg-network

  db-replica1:
    image: bitnami/postgresql-repmgr:15
    container_name: db-replica1
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=admin
      - POSTGRESQL_USERNAME=repuser
      - POSTGRESQL_PASSWORD=reppassword
      - POSTGRESQL_DATABASE=mydb
      - REPMGR_PASSWORD=reppassword
      - REPMGR_PRIMARY_HOST=db-master
      - REPMGR_NODE_ID=2
      - REPMGR_NODE_NAME=db-replica1-2
      - REPMGR_PARTNER_NODES=db-master,db-replica1,db-replica2
      - REPMGR_NODE_NETWORK_NAME=db-replica1
    depends_on:
      - db-master
    networks:
      - pg-network

  db-replica2:
    image: bitnami/postgresql-repmgr:15
    container_name: db-replica2
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=admin
      - POSTGRESQL_USERNAME=repuser
      - POSTGRESQL_PASSWORD=reppassword
      - POSTGRESQL_DATABASE=mydb
      - REPMGR_PASSWORD=reppassword
      - REPMGR_PRIMARY_HOST=db-master
      - REPMGR_NODE_ID=3
      - REPMGR_NODE_NAME=db-replica2-3
      - REPMGR_PARTNER_NODES=db-master,db-replica1,db-replica2
      - REPMGR_NODE_NETWORK_NAME=db-replica2
    depends_on:
      - db-master
    networks:
      - pg-network

  pgpool:
    image: bitnami/pgpool:4
    container_name: pgpool
    environment:
      - PGPOOL_BACKEND_NODES=0:db-master:5432,1:db-replica1:5432,2:db-replica2:5432
      - PGPOOL_SR_CHECK_USER=repuser
      - PGPOOL_SR_CHECK_PASSWORD=reppassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_LOG_CONNECTIONS=yes
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=admin123
      - PGPOOL_POSTGRES_USERNAME=repuser
      - PGPOOL_POSTGRES_PASSWORD=reppassword
    ports:
      - "5433:5432"
    depends_on:
      - db-master
      - db-replica1
      - db-replica2
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
