version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: patroni-etcd
    command: etcd --name infra0 --initial-advertise-peer-urls http://0.0.0.0:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379 --initial-cluster infra0=http://0.0.0.0:2380
    ports:
      - "2379:2379"
      - "2380:2380"

  patroni1:
    image: patroni/patroni:latest  # ✅ Koristi ispravan image
    container_name: patroni1
    environment:
      PATRONI_SCOPE: pgcluster
      PATRONI_NAME: patroni1
      PATRONI_ETCD3_HOSTS: patroni-etcd:2379
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: repl_password
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: admin_password
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni1:5432
    depends_on:
      - etcd
    ports:
      - "5432:5432"

  patroni2:
    image: patroni/patroni:latest  # ✅ Koristi ispravan image
    container_name: patroni2
    environment:
      PATRONI_SCOPE: pgcluster
      PATRONI_NAME: patroni2
      PATRONI_ETCD3_HOSTS: patroni-etcd:2379
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: repl_password
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: admin_password
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni2:5432
    depends_on:
      - etcd
    ports:
      - "5433:5432"
